//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoToCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeItem
    {
        public int Id { get; set; }
        public Nullable<int> NodeId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
