//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoToCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.NodeItem = new HashSet<NodeItem>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string Question { get; set; }
        public string Direction { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ImagePath { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<NodeItem> NodeItem { get; set; }
    }
}
